"""Step 5b LLM-backed VP Portfolio Scoring.

Evaluates and ranks the VP alternatives generated by Step 5a on five
desirability criteria aligned with Strategyzer Value Proposition Design.
Produces rankings with LLM recommendations for consultant selection.
"""
from __future__ import annotations

import json
from typing import Any, Literal

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from backend.app.llm.retry import invoke_with_retry
from backend.app.skills.loader import PromptAssetLoader
from backend.app.state import BMIWorkflowState


# ---------------------------------------------------------------------------
# Structured output schemas
# ---------------------------------------------------------------------------

class VPScore(BaseModel):
    """Scoring result for a single VP alternative."""
    alternative_name: str = Field(description="Name of the VP alternative being scored")
    coverage_score: str = Field(description="High, Medium, or Low")
    evidence_score: str = Field(description="High, Medium, or Low")
    pattern_fit_score: str = Field(description="High, Medium, or Low")
    differentiation_score: str = Field(description="High, Medium, or Low")
    testability_score: str = Field(description="High, Medium, or Low")
    overall_recommendation: str = Field(
        description="Recommended, Worth exploring, or Deprioritize"
    )
    rationale: str = Field(description="Brief rationale for this scoring")


class VPScoringOutput(BaseModel):
    """Complete Step 5b output: VP Scoring and Ranking."""
    rankings: list[VPScore] = Field(description="One score per VP alternative")
    recommended_indices: list[int] = Field(
        description="0-based indices of recommended alternatives (1-2 items)"
    )
    comparative_summary: str = Field(
        description="Comparative analysis of strengths and trade-offs across alternatives"
    )


# ---------------------------------------------------------------------------
# Prompt construction
# ---------------------------------------------------------------------------

def _format_alternatives_for_scoring(vp_alternatives: list[dict[str, Any]]) -> str:
    """Format VP alternatives as a structured prompt section for scoring."""
    sections: list[str] = []
    for i, alt in enumerate(vp_alternatives):
        lines = [
            f"### Alternative {i + 1}: {alt.get('name', f'VP {i + 1}')}",
            f"- **Pattern Flavor:** {alt.get('pattern_flavor_applied', 'N/A')}",
            f"- **Target Segment:** {alt.get('target_segment', 'N/A')}",
            f"- **Primary Job Focus:** {alt.get('primary_job_focus', 'N/A')}",
            f"- **Context:** {alt.get('context_scenario', 'N/A')}",
            f"- **Strategic Rationale:** {alt.get('strategic_rationale', 'N/A')}",
            f"- **Pattern Coherence:** {alt.get('pattern_coherence_note', 'N/A')}",
        ]
        # Products/Services
        ps_list = alt.get("products_services", [])
        if ps_list:
            lines.append("- **Products & Services:**")
            for ps in ps_list:
                lines.append(f"  - [{ps.get('type', '')}] {ps.get('product_service', '')} ({ps.get('relevance', '')})")
        # Pain Relievers
        pr_list = alt.get("pain_relievers", [])
        if pr_list:
            lines.append("- **Pain Relievers:**")
            for pr in pr_list:
                lines.append(f"  - [{pr.get('type', '')}] {pr.get('pain_reliever', '')} → addresses: {pr.get('pain_addressed', '')}")
        # Gain Creators
        gc_list = alt.get("gain_creators", [])
        if gc_list:
            lines.append("- **Gain Creators:**")
            for gc in gc_list:
                lines.append(f"  - [{gc.get('type', '')}] {gc.get('gain_creator', '')} → addresses: {gc.get('gain_addressed', '')}")
        # Ad-Lib
        ad_lib = alt.get("ad_lib_prototype", {})
        if ad_lib:
            lines.append(f"- **Ad-Lib:** {ad_lib.get('statement', 'N/A')}")

        sections.append("\n".join(lines))
    return "\n\n".join(sections)


def _build_messages(state: BMIWorkflowState) -> list[SystemMessage | HumanMessage]:
    vp_alternatives = state.get("vp_alternatives", [])
    if not vp_alternatives:
        raise ValueError("VP alternatives are required for Step 5b")

    skill_asset = PromptAssetLoader().load_step_prompt("step5b_vp_scoring")
    selected_patterns = ", ".join(state.get("selected_patterns", [])) or "approved patterns"
    alternatives_text = _format_alternatives_for_scoring(vp_alternatives)

    system_prompt = (
        f"{skill_asset.body}\n\n"
        "You are the CXIF Value Proposition Scoring agent.\n"
        "Evaluate each VP alternative on the 5 criteria described above.\n"
        "Be honest and evidence-based. Do not inflate scores.\n"
        "Recommend 1-2 alternatives as primary tracks for Business Model Canvas design.\n"
    )

    customer_profile = str(state.get("customer_profile", ""))
    voc_data = str(state.get("voc_data", ""))[:2000]

    user_prompt = (
        f"## Selected Patterns: {selected_patterns}\n\n"
        f"## VP Alternatives to Score\n{alternatives_text}\n\n"
        f"## Customer Empathy Profile (for coverage assessment)\n{customer_profile}\n\n"
        f"## Voice of Customer Evidence (for evidence grounding assessment)\n{voc_data}\n\n"
        "Score all alternatives and provide recommendations."
    )
    return [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)]


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------

def _render_rankings(result: VPScoringOutput) -> str:
    """Render rankings to markdown for display."""
    lines = [
        "# VP Portfolio Scoring",
        "",
        "## Rankings",
        "",
        "| # | Alternative | Coverage | Evidence | Pattern Fit | Differentiation | Testability | Recommendation |",
        "|---|-------------|----------|----------|-------------|-----------------|-------------|----------------|",
    ]
    for i, score in enumerate(result.rankings):
        rec_marker = " ⭐" if i in result.recommended_indices else ""
        lines.append(
            f"| {i + 1} | {score.alternative_name}{rec_marker} | {score.coverage_score} "
            f"| {score.evidence_score} | {score.pattern_fit_score} "
            f"| {score.differentiation_score} | {score.testability_score} "
            f"| {score.overall_recommendation} |"
        )

    lines.extend(["", "## Comparative Summary", "", result.comparative_summary])

    # Individual rationales
    lines.extend(["", "## Scoring Rationale", ""])
    for i, score in enumerate(result.rankings):
        lines.append(f"**{score.alternative_name}:** {score.rationale}")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Core execution
# ---------------------------------------------------------------------------

def run_step5b_llm(state: BMIWorkflowState, llm: BaseChatModel) -> BMIWorkflowState:
    """Run Step 5b VP Portfolio Scoring via the LLM."""
    messages = _build_messages(state)
    structured_llm = llm.with_structured_output(VPScoringOutput)
    result: VPScoringOutput = invoke_with_retry(
        structured_llm, messages, step_name="step5b_scoring"
    )

    # Validate recommended_indices are in range
    num_alts = len(state.get("vp_alternatives", []))
    valid_indices = [i for i in result.recommended_indices if 0 <= i < num_alts]
    if not valid_indices:
        valid_indices = [0]  # Fallback: recommend first alternative

    vp_rankings = [score.model_dump() for score in result.rankings]

    return {
        **state,
        "current_step": "vp_scoring",
        "vp_rankings": vp_rankings,
        "vp_recommended": valid_indices,
        "selected_vp_indices": valid_indices,
        "vp_scoring_summary": _render_rankings(result),
    }
