"""Step 7 LLM-backed Precoil EMT assumption mapping.

Uses the precoil-emt SKILL to generate 9 DVF assumptions (3 Desirability,
3 Viability, 3 Feasibility) grounded in the upstream Business Model Canvas
and Fit Assessment.  The Importance × Evidence Map and DVF Tensions are
generated by the LLM and rendered deterministically to ensure the format
is parseable by Step 8.
"""
from __future__ import annotations

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from backend.app.patterns.loader import PatternLibraryLoader
from backend.app.skills.loader import PromptAssetLoader
from backend.app.state import BMIWorkflowState


# ---------------------------------------------------------------------------
# Constants — must match values expected by Step 8 parser
# ---------------------------------------------------------------------------

_VALID_CATEGORIES = {"Desirability", "Viability", "Feasibility"}
_CATEGORY_LABEL = {"Desirability": "Desirable", "Viability": "Viable", "Feasibility": "Feasible"}
_VALID_QUADRANTS = {"Test first", "Monitor", "Deprioritize", "Safe zone"}


# ---------------------------------------------------------------------------
# Structured output schemas
# ---------------------------------------------------------------------------

class DVFAssumption(BaseModel):
    assumption: str = Field(description="Must start with 'I believe'. Statement about the business model.")
    rationale: str = Field(description="What happens if this assumption is wrong")
    quadrant: str = Field(description="One of: Test first, Monitor, Deprioritize, Safe zone")


class DVFCategory(BaseModel):
    category: str = Field(description="Desirability, Viability, or Feasibility")
    assumptions: list[DVFAssumption] = Field(description="Exactly 3 assumptions for this category", min_length=3, max_length=3)


class Step7Output(BaseModel):
    """Complete Step 7 output: 9 DVF assumptions + tension analysis."""
    categories: list[DVFCategory] = Field(description="Exactly 3 categories: Desirability, Viability, Feasibility", min_length=3, max_length=3)
    dvf_tension: str = Field(description="Analysis of the strongest tension between DVF dimensions")


# ---------------------------------------------------------------------------
# Prompt construction
# ---------------------------------------------------------------------------

def _build_messages(state: BMIWorkflowState) -> list[SystemMessage | HumanMessage]:
    bmc = str(state.get("business_model_canvas", ""))
    fit = str(state.get("fit_assessment", ""))
    if not bmc.strip():
        raise ValueError("Business Model Canvas is required for Step 7")

    skill_asset = PromptAssetLoader().load_skill_asset("precoil-emt")
    selected_patterns = ", ".join(state.get("selected_patterns", [])) or "approved patterns"

    # Load pattern library to validate DVF categories
    library = PatternLibraryLoader().load_library("precoil-emt-pattern-library.json").data
    category_names = {cat["name"] for cat in library["dvf_categories"]["categories"]}
    if category_names != _VALID_CATEGORIES:
        raise ValueError(f"Unexpected DVF categories: {category_names}")

    system_prompt = (
        f"{skill_asset.body}\n\n"
        "You are the Precoil EMT risk mapping agent for the BMI consultant workflow.\n"
        "Your task: extract the riskiest assumptions from the Business Model Canvas and Fit Assessment.\n\n"
        "RULES:\n"
        "- Generate EXACTLY 3 categories: Desirability, Viability, Feasibility.\n"
        "- Generate EXACTLY 3 assumptions per category (9 total).\n"
        "- Every assumption MUST start with 'I believe'.\n"
        "- Assign each assumption a quadrant: Test first, Monitor, Deprioritize, or Safe zone.\n"
        "- At least 1 assumption per category should be 'Test first'.\n"
        "- The DVF tension should identify the strongest conflict between dimensions.\n"
        "- Ground assumptions in the actual Business Model Canvas content.\n"
        f"- Reference {selected_patterns} where relevant.\n"
        "- Do not fabricate assumptions unrelated to the business model."
    )

    user_prompt = (
        f"Selected patterns: {selected_patterns}\n\n"
        f"Business Model Canvas:\n{bmc}\n\n"
        f"Fit Assessment:\n{fit}\n\n"
        f"Customer Profile:\n{state.get('customer_profile', '')}"
    )
    return [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)]


# ---------------------------------------------------------------------------
# Markdown rendering — deterministic format for Step 8 compatibility
# ---------------------------------------------------------------------------

def _render_assumptions(output: Step7Output, selected_patterns: list[str]) -> str:
    pattern_context = ", ".join(selected_patterns) or "approved patterns"
    lines: list[str] = []

    # DVF sections with assumption tables
    for cat in output.categories:
        label = _CATEGORY_LABEL.get(cat.category, cat.category)
        lines.extend([
            f"## {cat.category}",
            "| Category | Assumption | Rationale |",
            "|----------|------------|-----------|",
        ])
        for assumption in cat.assumptions:
            text = assumption.assumption if assumption.assumption.startswith("I believe") else f"I believe {assumption.assumption}"
            lines.append(f"| {label} | {text} | {assumption.rationale} |")
        lines.append("")

    # DVF Tensions
    lines.extend([
        "## DVF Tensions",
        output.dvf_tension,
        "",
    ])

    # Importance × Evidence Map — parseable by Step 8
    lines.extend([
        "## Importance × Evidence Map",
        "| Assumption | Category | Quadrant |",
        "|------------|----------|----------|",
    ])
    for cat in output.categories:
        for assumption in cat.assumptions:
            text = assumption.assumption if assumption.assumption.startswith("I believe") else f"I believe {assumption.assumption}"
            lines.append(f"| {text} | {cat.category} | {assumption.quadrant} |")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Core execution
# ---------------------------------------------------------------------------

def run_step7_llm(state: BMIWorkflowState, llm: BaseChatModel) -> BMIWorkflowState:
    """Run Step 7 Precoil EMT assumption mapping via the LLM."""
    messages = _build_messages(state)
    structured_llm = llm.with_structured_output(Step7Output)
    result: Step7Output = structured_llm.invoke(messages)

    selected_patterns = state.get("selected_patterns", [])

    return {
        **state,
        "current_step": "risk_map",
        "assumptions": _render_assumptions(result, selected_patterns),
    }
