"""Step 7 LLM-backed Precoil EMT assumption mapping.

Uses the precoil-emt SKILL to generate 9 DVF assumptions (3 Desirability,
3 Viability, 3 Feasibility) grounded in the upstream Business Model Canvas
and Fit Assessment.  The Importance × Evidence Map and DVF Tensions are
generated by the LLM and rendered deterministically to ensure the format
is parseable by Step 8.
"""
from __future__ import annotations

from typing import Literal

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from backend.app.patterns.loader import PatternLibraryLoader
from backend.app.skills.loader import PromptAssetLoader
from backend.app.llm.retry import invoke_with_retry
from backend.app.state import BMIWorkflowState


# ---------------------------------------------------------------------------
# Constants — must match values expected by Step 8 parser
# ---------------------------------------------------------------------------

_VALID_CATEGORIES = {"Desirability", "Viability", "Feasibility"}
_CATEGORY_LABEL = {"Desirability": "Desirable", "Viability": "Viable", "Feasibility": "Feasible"}
_VALID_QUADRANTS = {"Test first", "Monitor", "Deprioritize", "Safe zone"}


# ---------------------------------------------------------------------------
# Structured output schemas
# ---------------------------------------------------------------------------

class DVFAssumption(BaseModel):
    assumption: str = Field(description="Must start with 'I believe'. Statement about the business model.")
    rationale: str = Field(description="What happens if this assumption is wrong")
    suggested_quadrant: Literal["Test first", "Monitor", "Deprioritize", "Safe zone"] = Field(
        description="LLM suggestion only — the consultant must confirm placement. "
        "One of: Test first, Monitor, Deprioritize, Safe zone"
    )


class DVFCategory(BaseModel):
    category: str = Field(description="Desirability, Viability, or Feasibility")
    assumptions: list[DVFAssumption] = Field(description="Exactly 3 assumptions for this category", min_length=3, max_length=3)


class DVFTension(BaseModel):
    tension: str = Field(description="1-2 sentence description of the strongest conflict")
    assumption_a: str = Field(description="First assumption involved in the tension, referenced by its text")
    assumption_b: str = Field(description="Second assumption involved in the tension, referenced by its text")
    categories_in_conflict: str = Field(description="E.g. 'Desirability vs Viability'")


class Step7Output(BaseModel):
    """Complete Step 7 output: 9 DVF assumptions + tension analysis."""
    categories: list[DVFCategory] = Field(description="Exactly 3 categories: Desirability, Viability, Feasibility", min_length=3, max_length=3)
    dvf_tensions: list[DVFTension] = Field(
        description="At least 1 tension between DVF dimensions, referencing specific assumptions",
        min_length=1
    )


# ---------------------------------------------------------------------------
# Prompt construction
# ---------------------------------------------------------------------------

def _build_messages(state: BMIWorkflowState) -> list[SystemMessage | HumanMessage]:
    bmc = str(state.get("business_model_canvas", ""))
    fit = str(state.get("fit_assessment", ""))
    if not bmc.strip():
        raise ValueError("Business Model Canvas is required for Step 7")

    skill_asset = PromptAssetLoader().load_step_prompt("step7_risk_map")
    selected_patterns = ", ".join(state.get("selected_patterns", [])) or "approved patterns"

    # Load pattern library to validate DVF categories
    library = PatternLibraryLoader().load_library("precoil-emt-pattern-library.json").data
    category_names = {cat["name"] for cat in library["dvf_categories"]["categories"]}
    if category_names != _VALID_CATEGORIES:
        raise ValueError(f"Unexpected DVF categories: {category_names}")

    system_prompt = (
        f"{skill_asset.body}\n\n"
        "You are the Precoil EMT risk mapping agent for the BMI consultant workflow.\n"
        "Your task: extract the riskiest assumptions from the Business Model Canvas and Fit Assessment.\n\n"
        "RULES:\n"
        "- Generate EXACTLY 3 categories: Desirability, Viability, Feasibility.\n"
        "- Generate EXACTLY 3 assumptions per category (9 total).\n"
        "- Every assumption MUST start with 'I believe'.\n"
        "- Assign each assumption a quadrant: Test first, Monitor, Deprioritize, or Safe zone.\n"
        "- Your quadrant assignments are SUGGESTIONS. Label them as such.\n"
        "- You cannot objectively assess what evidence the organization has. Err toward\n"
        "  'Test first' for high-impact assumptions where evidence strength is ambiguous.\n"
        "- At least 1 assumption per category should be 'Test first'.\n"
        "- The DVF tensions should identify conflicts between dimensions, referencing specific assumptions.\n"
        "- Ground assumptions in the actual Business Model Canvas content.\n"
        f"- Reference {selected_patterns} where relevant.\n"
        "- Do not fabricate assumptions unrelated to the business model."
    )

    user_prompt = (
        f"Selected patterns: {selected_patterns}\n\n"
        f"Business Model Canvas:\n{bmc}\n\n"
        f"Fit Assessment:\n{fit}\n\n"
        f"Customer Profile:\n{state.get('customer_profile', '')}"
    )
    return [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)]


# ---------------------------------------------------------------------------
# Markdown rendering — deterministic format for Step 8 compatibility
# ---------------------------------------------------------------------------

def _render_assumptions(output: Step7Output, selected_patterns: list[str]) -> str:
    pattern_context = ", ".join(selected_patterns) or "approved patterns"
    lines: list[str] = []

    # DVF sections with assumption tables
    for cat in output.categories:
        label = _CATEGORY_LABEL.get(cat.category, cat.category)
        lines.extend([
            f"## {cat.category}",
            "| Category | Assumption | Rationale |",
            "|----------|------------|-----------|",
        ])
        for assumption in cat.assumptions:
            text = assumption.assumption if assumption.assumption.startswith("I believe") else f"I believe {assumption.assumption}"
            lines.append(f"| {label} | {text} | {assumption.rationale} |")
        lines.append("")

    # DVF Tensions
    lines.extend([
        "## DVF Tensions",
        "| Tension | Assumptions in Conflict | Categories |",
        "|---------|------------------------|------------|",
    ])
    for t in output.dvf_tensions:
        lines.append(f"| {t.tension} | {t.assumption_a} / {t.assumption_b} | {t.categories_in_conflict} |")
    lines.append("")

    # Importance × Evidence Map — parseable by Step 8
    lines.extend([
        "## Importance × Evidence Map (Suggested — Review Required)",
        "",
        "The following quadrant placements are the LLM's best assessment. The consultant",
        "should review and adjust based on organizational knowledge about what evidence",
        "actually exists and which assumptions are truly vital to the business model.",
        "",
        "| Assumption | Category | Suggested Quadrant |",
        "|------------|----------|--------------------|",
    ])
    for cat in output.categories:
        for assumption in cat.assumptions:
            text = assumption.assumption if assumption.assumption.startswith("I believe") else f"I believe {assumption.assumption}"
            lines.append(f"| {text} | {cat.category} | {assumption.suggested_quadrant} |")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Core execution
# ---------------------------------------------------------------------------

def run_step7_llm(state: BMIWorkflowState, llm: BaseChatModel) -> BMIWorkflowState:
    """Run Step 7 Precoil EMT assumption mapping via the LLM."""
    messages = _build_messages(state)
    structured_llm = llm.with_structured_output(Step7Output)
    result: Step7Output = invoke_with_retry(structured_llm, messages, step_name="step7_risk")

    selected_patterns = state.get("selected_patterns", [])

    return {
        **state,
        "current_step": "risk_map",
        "assumptions": _render_assumptions(result, selected_patterns),
        "step7_structured": result.model_dump(),
    }
